name: Romit Girdhar
theme: jekyll-theme-slate
permalink: /:year/:month/:day/:title
url: http://blog.romitg.com
baseurl: ""
name: Data Geek's Blog | Romit Girdhar
description: All things data!
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  github: romitgirdhar
  twitter: romitgirdhar
  stackoverflow: users/1909743/datageek
disqus: romitg-blog
sass:
  style: :compressed
kramdown:
  input: GFM
  css_class: 'highlight'
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME